# Generated by Django 6.0.5 on 2026-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_nin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('verifier', 'Verification Officer'), ('admin', 'LGA Administrator'), ('superadmin', 'Super Administrator')], default='student', max_length=20),
        ),
    ]
