# Generated by Django 6.0.5 on 2026-05-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowermentDetails',
            fields=[
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empowerment_details', serialize=False, to='applications.application')),
                ('trade_or_skill', models.CharField(max_length=120)),
                ('training_provider', models.CharField(blank=True, max_length=200)),
                ('training_duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prior_experience', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantDetails',
            fields=[
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='grant_details', serialize=False, to='applications.application')),
                ('business_name', models.CharField(max_length=200)),
                ('business_stage', models.CharField(choices=[('idea', 'Idea Stage'), ('startup', 'Startup / Early-stage'), ('growth', 'Growth Stage'), ('mature', 'Established')], max_length=30)),
                ('business_description', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('intended_use', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarshipDetails',
            fields=[
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scholarship_details', serialize=False, to='applications.application')),
                ('institution_name', models.CharField(max_length=200)),
                ('course_of_study', models.CharField(max_length=200)),
                ('current_level', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('admission_year', models.IntegerField()),
                ('matric_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
