# Generated by Django 6.0.5 on 2026-06-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_empowermentdetails_grantdetails_scholarshipdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowermentdetails',
            name='business_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empowermentdetails',
            name='equipment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
