# Generated by Django 6.0.5 on 2026-10-04 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_applications_scheme_sent_idx_application_scheme__7ca57e_idx_and_more'),
        ('schemes', '0003_cycle_activated_at'),
        ('students', '0012_student_entry_level_student_faculty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('eligibility_check', 'Under Eligibility Check'), ('double_dip_flag', 'Flagged — Multiple Benefit Conflict'), ('document_review', 'Documents Under Review'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiver_required', 'Awaiting Award Waiver'), ('withdrawn', 'Withdrawn by Applicant')], default='draft', max_length=30)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('self_declaration_received_support', models.BooleanField(null=True)),
                ('self_declaration_details', models.JSONField(blank=True, default=list)),
                ('attestation_agreed', models.BooleanField(default=False)),
                ('attestation_at', models.DateTimeField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('eligibility_passed', models.BooleanField(null=True)),
                ('eligibility_details', models.JSONField(default=dict)),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_scheme_ids', models.JSONField(default=list)),
                ('waiver_submitted', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_code', models.CharField(blank=True, default='', max_length=10)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('name_match_passed', models.BooleanField(default=False)),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('course_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('current_level', models.CharField(blank=True, default='', max_length=20)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('matric_number', models.CharField(blank=True, default='', max_length=50)),
                ('trade_or_skill', models.CharField(blank=True, default='', max_length=120)),
                ('training_provider', models.CharField(blank=True, default='', max_length=200)),
                ('training_duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prior_experience', models.TextField(blank=True, default='')),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_stage', models.CharField(blank=True, default='', max_length=30)),
                ('business_description', models.TextField(blank=True, default='')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('intended_use', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schemes.scholarshipscheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='application_status_db7a61_idx'), models.Index(fields=['student', '-created_at'], name='application_student_04264e_idx'), models.Index(fields=['scheme', 'status'], name='application_scheme__a1bf4b_idx'), models.Index(fields=['scheme', '-created_at'], name='application_scheme__86d1eb_idx')],
            },
        ),
    ]
