# Generated by Django 6.0.5 on 2026-10-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_applications_scheme_sent_idx_application_scheme__7ca57e_idx_and_more'),
        ('schemes', '0003_cycle_activated_at'),
        ('students', '0012_student_entry_level_student_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationIndex',
            fields=[
                ('application_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('eligibility_check', 'Under Eligibility Check'), ('double_dip_flag', 'Flagged — Multiple Benefit Conflict'), ('document_review', 'Documents Under Review'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiver_required', 'Awaiting Award Waiver'), ('withdrawn', 'Withdrawn by Applicant')], max_length=30)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('eligibility_passed', models.BooleanField(null=True)),
                ('has_conflict', models.BooleanField(default=False)),
                ('waiver_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemes.scholarshipscheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='application_status_843824_idx'), models.Index(fields=['student', '-created_at'], name='application_student_711d4e_idx'), models.Index(fields=['scheme', 'status'], name='application_scheme__d55cb8_idx')],
            },
        ),
    ]
