# Generated by Django 6.0.5 on 2026-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application', 'Application'), ('deadline', 'Deadline'), ('programme', 'Programme'), ('profile', 'Profile'), ('system', 'System'), ('alert', 'Alert'), ('welcome', 'Welcome'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected')], default='system', max_length=30),
        ),
    ]
