# Generated by Django 6.0.5 on 2026-05-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_record',
            new_name='AcademicRecord',
        ),
    ]
