# Generated by Django 6.0.5 on 2026-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='state_of_origin',
            new_name='certificate',
        ),
        migrations.AddField(
            model_name='student',
            name='nin_hash',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
