# Generated by Django 6.0.5 on 2026-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
