# Generated by Django 6.0.5 on 2026-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
