# Generated by Django 6.0.5 on 2026-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_academic_record_academicrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
