# Generated by Django 6.0.5 on 2026-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_state_of_origin_student_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
