# Generated by Django 6.0.5 on 2026-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
