# Generated by Django 6.0.5 on 2026-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_account_name_student_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
