# Generated by Django 6.0.5 on 2026-07-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_passports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
    ]
