# Generated by Django 6.0.5 on 2026-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_delete_academicrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='nin_slip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
