# Generated by Django 6.0.5 on 2026-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_date_of_birth_remove_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='programme_duration_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('hnd', 'HND (top-up)'), ('postgraduate_taught', 'Postgraduate (taught)'), ('postgraduate_research', 'Postgraduate (research)')], max_length=30),
        ),
    ]
