# Generated by Django 6.0.5 on 2026-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipscheme',
            name='award_type',
            field=models.CharField(choices=[('scholarship', 'Scholarship (Academic)'), ('empowerment', 'Empowerment / Vocational Training'), ('grant', 'Grant')], default='scholarship', max_length=20),
        ),
    ]
