# Generated by Django 6.0.5 on 2026-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipscheme',
            name='applicable_programme_types',
            field=models.JSONField(blank=True, default=list, help_text='Subset of undergraduate / hnd / postgraduate_taught / postgraduate_research. Empty list = undergrad only.'),
        ),
        migrations.AddField(
            model_name='scholarshipscheme',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarshipscheme',
            name='min_renewal_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly renewal threshold; falls back to eligibility min_cgpa when blank.', max_digits=4, null=True),
        ),
    ]
