# Generated by Django 6.0.5 on 2026-06-08 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_alter_scholarshipscheme_award_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('file', 'File Upload'), ('checkbox', 'Checkbox'), ('number', 'Number Input')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='schemes.scholarshipscheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
