# Generated by Django 6.0.5 on 2026-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scholarshipscheme_applicable_programme_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
