# Generated by Django 6.0.5 on 2026-10-01 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0002_scholarshipscheme_applicable_programme_types_and_more'),
        ('students', '0012_student_entry_level_student_faculty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(unique=True)),
                ('total_years', models.PositiveSmallIntegerField()),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_cgpa_snapshot', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_year_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('suspended_reason', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('tenure_confidence', models.CharField(default='confirmed', max_length=20)),
                ('tenure_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='schemes.scholarshipscheme')),
                ('start_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards_started', to='schemes.cycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AwardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='awards.award')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_index', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('pending_renewal', 'Pending renewal'), ('pending_verification', 'Pending verification'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('withheld', 'Withheld'), ('cancelled', 'Cancelled')], default='pending_renewal', max_length=30)),
                ('submitted_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('submitted_cgpa_scale', models.CharField(blank=True, choices=[('5.0', '5.0 scale'), ('4.0', '4.0 scale')], default='5.0', max_length=4)),
                ('submitted_cgpa_normalized', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('submitted_level', models.CharField(blank=True, max_length=20)),
                ('transcript', models.FileField(blank=True, null=True, upload_to='award_renewals/')),
                ('resubmission_count', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_note', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_ref', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='awards.award')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='schemes.cycle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year_index'],
            },
        ),
        migrations.CreateModel(
            name='AwardAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='award_appeals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='awards.award')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='awards.awardinstallment')),
            ],
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['status'], name='awards_awar_status_41da2f_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['scheme', 'status'], name='awards_awar_scheme__f539d0_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['student', 'status'], name='awards_awar_student_310c7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(('current_year_index__lte', models.F('total_years'))), name='award_year_index_within_total'),
        ),
        migrations.AddIndex(
            model_name='awardevent',
            index=models.Index(fields=['award', 'created_at'], name='awards_awar_award_i_b896d4_idx'),
        ),
        migrations.AddIndex(
            model_name='awardinstallment',
            index=models.Index(fields=['status'], name='awards_awar_status_04acd6_idx'),
        ),
        migrations.AddIndex(
            model_name='awardinstallment',
            index=models.Index(fields=['cycle', 'status'], name='awards_awar_cycle_i_ae0825_idx'),
        ),
        migrations.AddIndex(
            model_name='awardinstallment',
            index=models.Index(fields=['award', 'year_index'], name='awards_awar_award_i_3c5433_idx'),
        ),
        migrations.AddConstraint(
            model_name='awardinstallment',
            constraint=models.UniqueConstraint(fields=('award', 'year_index'), name='unique_installment_per_year'),
        ),
        migrations.AddIndex(
            model_name='awardappeal',
            index=models.Index(fields=['status'], name='awards_awar_status_118189_idx'),
        ),
    ]
